preferred_syntax = :scss
http_path = '/'
css_dir = 'assets/css'
sass_dir = 'assets/scss'
images_dir = 'assets/images'
javascripts_dir = 'assets/js'
relative_assets = true
line_comments = false
# output_style = :compressed
